name: Lumify
markdown: redcarpet
pygments: true
safe: true
lsi: false
timezone: America/New_York
google_analytics_ua: UA-74388-18
paginate: 10
paginate_path: "blog/page:num"
permalink: /blog/:year/:month/:day/:title
